### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by venning** [gitterHQ/tentacles#1]
[This line](https://github.com/gitterHQ/tentacles/blob/c21bf60521aacae9d9b84c968264d09237dc882f/lib/client.js#L122) mispells the attribute `response` as `respone`.

I don't know how to test this, but this is presumably not what is supposed to happen.

**Comment by suprememoocow** [comment]
Fix published on npm as `tentacles@0.2.8`. Thanks for the report and the PR @venning

**Comment by venning** [comment]
Absolutely.  Thanks for Tentacles.
